[package]
name = "katana"
version = "0.1.0"
edition = "2021"
authors = ["Judicaël AHYI <ludndev@gmail.com>"]

[lib]
name = "katana"
path = "src/lib.rs"

[[bin]]
name = "katana"
path = "src/main.rs"

[dependencies]
